/** One cached record. Vectors are always computed by the library; callers never pass one in, which keeps vector spaces from being mixed. */
export interface CacheEntry {
	readonly id: string;
	readonly scope: string;
	/** Text used for exact matching and recall (post-anonymization, if the caller anonymizes). */
	readonly matchText: string;
	readonly matchHash: string;
	/** PairEncoder space. */
	readonly matchVector: ReadonlyArray<number>;
	/** Whether a text answer or a tool plan is cached. */
	readonly kind: "answer" | "plan";
	/** Empty string when `kind === "plan"`. */
	readonly answer: string;
	/** Empty object when `kind === "plan"`. */
	readonly plan: Readonly<Record<string, string>>;
	readonly createdAt: number;
	readonly expiresAt: number | null;
	readonly meta?: Readonly<Record<string, string>> | undefined;
	/**
	 * When this entry was last reused. Used by `lru` eviction; always undefined under other policies.
	 *
	 * Not set on write — it would equal `createdAt` there, and storing it twice carries no
	 * information. Order on `lastUsedAt ?? createdAt`.
	 */
	readonly lastUsedAt?: number | undefined;
	/** How many times this entry has been reused. Used by `lfu` eviction; always undefined under other policies. */
	readonly useCount?: number | undefined;
}

export interface Candidate {
	readonly entry: CacheEntry;
	/** Cosine in PairEncoder space. */
	readonly similarity: number;
}

/**
 * The store interface. The in-memory implementation is for tests and calibration; production
 * implementations target pgvector.
 *
 * `searchNearest` must pre-filter inside the store: return only entries in the same scope that
 * have not expired. An expired row must never be returned, even if it has not been cleaned up yet.
 *
 * Writing your own carries three further hard requirements (see DESIGN.md): `put` must throw on a
 * duplicate id, `getByHash` must deterministically return the newest, and a non-finite vector
 * component must throw (use `assertFiniteVector` — silently coercing to 0 or storing it as-is
 * makes gate ③'s recall floor effectively nonexistent).
 */
export interface CacheStore {
	/**
	 * Fetch a candidate by normalized hash.
	 *
	 * **An implementation only has to look up by hash; the final comparison of the original text is
	 * `SemanticCache`'s job.** `matchHash` is not a cryptographic hash, and a collision would make
	 * "exact match" return a completely unrelated answer — while the entire value of this layer is
	 * that it carries zero risk of a false hit. So the library always re-compares `matchText` after
	 * receiving a candidate, rather than relying on any store implementation to remember to.
	 */
	/**
	 * Fetch a candidate by scope + normalized hash.
	 *
	 * **When several rows share one `(scope, matchHash)`, return the newest** (greatest
	 * `createdAt`, and greatest id within the same millisecond). Concurrent writes produce such
	 * duplicates, and "which one" has to be deterministic: if two store implementations answer
	 * differently here, gate ② hits a different answer in each.
	 */
	getByHash(scope: string, matchHash: string): Promise<CacheEntry | null>;
	/**
	 * Fetch by id. Like `getByHash`, this **returns only unexpired entries** — it is part of the
	 * read path (a caller comes back with the previous `entryId`), not a diagnostic entry point. To
	 * see the raw state including expired-but-uncleaned rows, use `InspectableCacheStore.all()`.
	 */
	getById(id: string): Promise<CacheEntry | null>;
	searchNearest(scope: string, vector: ReadonlyArray<number>, limit: number): Promise<Array<Candidate>>;
	/**
	 * Write one entry. **A duplicate id must throw — never silently drop, and never overwrite.**
	 *
	 * In this design `put` is never an upsert: ids are generated by the library, and no legitimate
	 * path writes the same id twice. So an id collision is always a bug (most likely an id
	 * generator colliding across processes). Silently dropping makes a cache entry vanish;
	 * overwriting lets one process rewrite an entry whose contents belong to another.
	 */
	put(entry: CacheEntry): Promise<void>;
	evict(id: string): Promise<void>;
	/**
	 * Clear one scope, returning how many rows were deleted.
	 *
	 * It is in the hot-path contract while `clear()` is not, because **this one is a production
	 * operation**: archiving a course, a teacher asking for a reset, a tenant closing an account all
	 * clear by scope. The argument-free clear-everything is the test-only one.
	 *
	 * **This is also the only invalidation-by-content path.** Entries record the space they belong
	 * to and nothing finer, so "the material changed" is answered by clearing that space, not by
	 * matching the entries that cite a particular document.
	 */
	clearScope(scope: string): Promise<number>;
	/**
	 * Delete expired rows, returning how many were deleted.
	 *
	 * The read path already keeps expired entries out, so this method **does not affect correctness,
	 * only storage footprint**: skip it and expired rows stay in the table forever, and on pgvector
	 * they additionally slow down the exact KNN scan within a scope. A periodic job calling it is
	 * enough.
	 */
	purgeExpired(): Promise<number>;
	/**
	 * Bookkeeping on a hit. **Must be a genuine no-op under `fifo`/`rr`** (no request, no write) —
	 * those policies need no write on the read path, callers call this unconditionally, and the
	 * policy knowledge stays in the store.
	 *
	 * `lru` updates `lastUsedAt`, `lfu` increments `useCount`. Return silently when the entry is
	 * gone: it may have just been evicted concurrently, and throwing on the whole hit path over one
	 * failed bookkeeping write is not worth it.
	 */
	touch(id: string): Promise<void>;
	/**
	 * Bring one scope back down to its capacity limit, returning how many rows were deleted.
	 * Returns 0 when no `eviction` is configured.
	 *
	 * The store calls this itself after `put`, so callers normally never touch it; it is exposed
	 * separately to make it testable, and so an operator can collect one scope by hand.
	 */
	evictOverCapacity(scope: string): Promise<number>;
}

/**
 * A store with introspection — tests, offline calibration and the lab need "clear" and "list
 * everything"; the production read path does not. Hence they are not in `CacheStore`: that is the
 * hot-path contract, and making every production implementation write an `all()` only tests call
 * is a pointless burden.
 *
 * Both methods are async. The in-memory implementation could do them synchronously, but a real
 * database cannot, and callers should not have to rewrite their awaits because the store
 * implementation changed.
 */
export interface InspectableCacheStore extends CacheStore {
	/** Clear everything. Not for production. */
	clear(): Promise<void>;
	/**
	 * List every entry, **including expired-but-uncleaned rows** — for UI display and assertions.
	 *
	 * **The order is part of the contract: ascending `createdAt`, ties broken by ascending `id`.**
	 * The two real-database implementations need an ORDER BY anyway (without one, pagination and
	 * "the most recent N" are both meaningless), while the in-memory one used to return insertion
	 * order — the two coincide exactly when entries are written in time order, so the divergence
	 * stayed invisible until a conformance script produced an entry with an earlier `createdAt`
	 * that was written last.
	 */
	all(): Promise<ReadonlyArray<CacheEntry>>;
}
